import { Inter } from "next/font/google";
import Theme from "./Theme";
import { Box } from "@mui/material";
import Navbar from "@/components/navbar/Navbar";
import "@/styles/globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/store/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Metronic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Theme>
            <Box display={"flex"}>
              <Box
                display={{ xs: "none", sm: "none", md: "block", lg: "block" }}
              >
                <Sidebar />
              </Box>
              <Box width={"100%"} id="main">
                <Navbar />
                <main>{children}</main>
                <Footer />
              </Box>
            </Box>
          </Theme>
        </ReduxProvider>
      </body>
    </html>
  );
}
