"use client";
import { Inter } from "next/font/google";
import Theme from "./Theme";
import { Box } from "@mui/material";
import Navbar from "@/components/navbar/Navbar";
import "../styles/globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Footer from "@/components/footer/Footer";
import { useState } from "react";
import { store } from "@/store/store";
import { Provider } from "react-redux";
import { usePathname } from "next/navigation";
import LandingPageNav from "@/components/landing-page-nav/LandingPageNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Medical",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const path = usePathname();

  const [isSidebarActive, setIsSidebarActive] = useState(false);

  const openSidebar = () => {
    setIsSidebarActive(true);
  };
  const closeSidebar = () => {
    setIsSidebarActive(false);
  };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Theme>
            {path === "/" ? (
              <Box>
                <LandingPageNav />
                <main>{children}</main>
                <Footer />
              </Box>
            ) : (
              <Box display={"flex"}>
                <Box
                  display={{ xs: "none", sm: "none", md: "block", lg: "block" }}
                  onMouseOver={openSidebar}
                  onMouseOut={closeSidebar}
                >
                  <Sidebar isActive={isSidebarActive} />
                </Box>
                <Box width={"100%"} id="main">
                  <Navbar />
                  <main>{children}</main>
                  <Footer />
                </Box>
              </Box>
            )}
          </Theme>
        </Provider>
      </body>
    </html>
  );
}
